language: python

python:
  - "2.7"

env:
  - VERSION="8.0" ODOO_REPO="odoo/odoo" INCLUDE="framework_agreement"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" INCLUDE="framework_agreement"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" EXCLUDE="framework_agreement"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" EXCLUDE="framework_agreement"

virtualenv:
  system_site_packages: true

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - git clone https://github.com/OCA/server-tools -b ${VERSION} $HOME/server-tools

script:
  - travis_run_flake8
  - travis_run_tests

after_success:
  coveralls
